/**
 * Autogenerated by Thrift for /disk/CacheLib/cachelib/external/fbthrift/thrift/lib/thrift/frozen.thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated @nocommit
 */
#pragma once
#include "thrift/lib/thrift/gen-cpp2/frozen_for_each_field.h"
#include "thrift/lib/thrift/gen-cpp2/frozen_visit_union.h"
#include "thrift/lib/thrift/gen-cpp2/frozen_visit_by_thrift_field_metadata.h"
