/**
 * Autogenerated by Thrift for /mnt/cfs/CacheLib/cachelib/external/fbthrift/thrift/lib/thrift/id.thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated @nocommit
 */
#pragma once

#include <thrift/lib/cpp2/gen/module_constants_h.h>

#include "thrift/lib/thrift/gen-cpp2/id_types.h"

namespace apache::thrift::type {

struct id_constants {

  static constexpr ::apache::thrift::type::ExternId const noId_ = static_cast<::apache::thrift::type::ExternId>(0);
  static constexpr ::apache::thrift::type::ExternId noId() {
    return noId_;
  }

};

} // namespace apache::thrift::type
