/**
 * Autogenerated by Thrift for /disk/CacheLib/cachelib/external/fbthrift/thrift/lib/thrift/reflection.thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated @nocommit
 */
#pragma once

#include <cstdint>

// BEGIN forward_declare
namespace apache::thrift::reflection {
class StructField;
class DataType;
class Schema;
} // namespace apache::thrift::reflection
// END forward_declare

// BEGIN forward_declare_enums
namespace apache::thrift::reflection {
enum class Type;
} // namespace apache::thrift::reflection
// END forward_declare_enums
