/**
 * Autogenerated by Thrift for /disk/CacheLib/cachelib/external/fbthrift/thrift/lib/thrift/serverdbginfo.thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated @nocommit
 */
#pragma once

// BEGIN forward_declare
namespace apache::thrift::serverdbginfo {
class RequestPileDbgInfo;
class ConcurrencyControllerDbgInfo;
class ExecutorDbgInfo;
class ResourcePoolDbgInfo;
class CPUConcurrencyControllerDbgInfo;
class ResourcePoolsDbgInfo;
} // namespace apache::thrift::serverdbginfo
// END forward_declare
