/**
 * Autogenerated by Thrift for /disk/CacheLib/cachelib/external/fbthrift/thrift/lib/thrift/serverdbginfo.thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated @nocommit
 */
#pragma once

#include <thrift/lib/cpp2/gen/module_constants_h.h>

#include "thrift/lib/thrift/gen-cpp2/serverdbginfo_types.h"

namespace apache::thrift::serverdbginfo {

struct serverdbginfo_constants {

};

} // namespace apache::thrift::serverdbginfo
