/**
 * Autogenerated by Thrift for /mnt/cfs/CacheLib/cachelib/external/fbthrift/thrift/lib/thrift/type_rep.thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated @nocommit
 */
#pragma once

#include <vector>

#include <thrift/lib/cpp2/gen/module_metadata_h.h>
#include "thrift/lib/thrift/gen-cpp2/type_rep_types.h"
#include "thrift/lib/thrift/gen-cpp2/id_metadata.h"
#include "thrift/lib/thrift/gen-cpp2/standard_metadata.h"


namespace apache {
namespace thrift {
namespace detail {
namespace md {

template <>
class StructMetadata<::apache::thrift::type::ProtocolUnion>
    : private EmptyMetadata {
 public:
  using EmptyMetadata::gen;
};
template <>
class StructMetadata<::apache::thrift::type::TypeStruct>
    : private EmptyMetadata {
 public:
  using EmptyMetadata::gen;
};
} // namespace md
} // namespace detail
} // namespace thrift
} // namespace apache
