/**
 * Autogenerated by Thrift for /mnt/cfs/CacheLib/cachelib/external/fbthrift/thrift/annotation/java.thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated @nocommit
 */
#pragma once

// BEGIN forward_declare
namespace facebook::thrift::annotation::java {
class Mutable;
class Annotation;
class BinaryString;
class Adapter;
class Wrapper;
class Recursive;
class FieldUseUnmangledName;
} // namespace facebook::thrift::annotation::java
// END forward_declare
