/**
 * Autogenerated by Thrift for /disk/CacheLib/cachelib/external/fbthrift/thrift/annotation/python.thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated @nocommit
 */
#pragma once

#include <vector>

#include <thrift/lib/cpp2/gen/module_metadata_h.h>
#include "thrift/annotation/gen-cpp2/python_types.h"


namespace apache {
namespace thrift {
namespace detail {
namespace md {

template <>
class StructMetadata<::facebook::thrift::annotation::python::Py3Hidden>
    : private EmptyMetadata {
 public:
  using EmptyMetadata::gen;
};
template <>
class StructMetadata<::facebook::thrift::annotation::python::Flags>
    : private EmptyMetadata {
 public:
  using EmptyMetadata::gen;
};
template <>
class StructMetadata<::facebook::thrift::annotation::python::Name>
    : private EmptyMetadata {
 public:
  using EmptyMetadata::gen;
};
template <>
class StructMetadata<::facebook::thrift::annotation::python::Adapter>
    : private EmptyMetadata {
 public:
  using EmptyMetadata::gen;
};
template <>
class StructMetadata<::facebook::thrift::annotation::python::UseCAPI>
    : private EmptyMetadata {
 public:
  using EmptyMetadata::gen;
};
} // namespace md
} // namespace detail
} // namespace thrift
} // namespace apache
