/**
 * Autogenerated by Thrift for /mnt/cfs/CacheLib/cachelib/external/fbthrift/thrift/annotation/thrift.thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated @nocommit
 */
#pragma once

#include <cstdint>

// BEGIN forward_declare
namespace facebook::thrift::annotation {
class Experimental;
class ReserveIds;
class RequiresBackwardCompatibility;
class TerseWrite;
class Box;
class Mixin;
class SerializeInFieldIdOrder;
class BitmaskEnum;
class ExceptionMessage;
class GenerateRuntimeSchema;
class InternBox;
class Serial;
class Uri;
class Priority;
class DeprecatedUnvalidatedAnnotations;
} // namespace facebook::thrift::annotation
// END forward_declare

// BEGIN forward_declare_enums
namespace facebook::thrift::annotation {
enum class RpcPriority;
} // namespace facebook::thrift::annotation
// END forward_declare_enums
